background {
    color = rgba(191724ee)
}

input-field {
    size = 250, 60
    rounding = 18
    outline_thickness = 1
    inner_color = rgba(31, 29, 46, 0.8)
    outer_color = rgba(110, 106, 134, 0.6)
    font_color = rgba(224, 222, 244, 1)
    placeholder_text = Password
    position = 0, -20
    halign = center
    valign = center
}

label {
    text = cmd[update:60000] echo "$(date +'%H:%M')"
    color = rgba(224, 222, 244, 1)
    font_size = 48
    position = 0, 100
    halign = center
    valign = center
}
